language: java

jdk:
  - oraclejdk7
  - openjdk7
  - openjdk6

script: mvn -f hello/pom.xml install

notifications:
  irc:
    channels:
      - "irc.freenode.org#jhurliman"
    on_success: change
    on_failure: always
    template:
      - "%{repository} (%{branch}:%{commit} by %{author}): %{message} (%{build_url})" 
