language: java

jdk:
  - oraclejdk7
  - openjdk7

script: mvn -f hellomaven/pom.xml test

notifications:
  irc:
    channels:
      - "irc.freenode.org#jhurliman"
    on_success: change
    on_failure: always
    template:
      - "%{repository} (%{branch}:%{commit} by %{author}): %{message} (%{build_url})" 
